
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGVzIjoiU3lzdGVtLlN0cmluZ1tdIiwibmJmIjoxNjA3Nzk1NDM5LCJleHAiOjE2MDg0MDAyMzksImlhdCI6MTYwNzc5NTQzOX0.D97W9BKCAeW_Q7eYV13Y078XAwGCJiGYUeeH7eZ4nZI
@tokenCustomer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJuYW1lIjoiMTIzMzMiLCJyb2xlcyI6IlN5c3RlbS5TdHJpbmdbXSIsIm5iZiI6MTYwNzc5OTE2NCwiZXhwIjoxNjA4NDAzOTY0LCJpYXQiOjE2MDc3OTkxNjR9.pQCsqkytiTP-CrCvMBNZyuTdlzYgoEEZ_YVf3OiGm5g

@tokenTIno = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJuYW1lIjoidGlub0BnbWFpbC5jb20iLCJyb2xlcyI6IlN5c3RlbS5TdHJpbmdbXSIsIm5iZiI6MTYwNzc5OTI2MiwiZXhwIjoxNjA4NDA0MDYyLCJpYXQiOjE2MDc3OTkyNjJ9.c4r9Yki42-hd3xjW9ibcL8--0mBa8DaLn5bAQ2YuMOo

###
POST http://localhost:4300/api/user/login HTTP/1.1
Content-Type: application/json

{
    "UserName" : "tino@gmail.com",
    "Password" : "tino@gmail.com"
}


#####


GET http://localhost:4300/api/user/profile HTTP/1.1
Content-Type: application/json
Authorization: bearer {{tokenCustomer}}

######




GET http://localhost:4300/api/user HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

######