// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ApsWebApp;

namespace ApsWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210615083003__changePembayaran")]
    partial class _changePembayaran
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ShareModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ShareModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("KaryawanId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NPWP")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telepon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KaryawanId");

                    b.HasIndex("UserId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("ShareModels.Gudang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Gudang");
                });

            modelBuilder.Entity("ShareModels.IncomingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ActualValue")
                        .HasColumnType("double");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int?>("PembelianId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PembelianId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("IncomingItem");
                });

            modelBuilder.Entity("ShareModels.Karyawan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telepon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Karyawan");
                });

            modelBuilder.Entity("ShareModels.Merk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Merk");
                });

            modelBuilder.Entity("ShareModels.OrderPembelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("OrderPembelian");
                });

            modelBuilder.Entity("ShareModels.OrderPembelianItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int?>("OrderPembelianId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quntity")
                        .HasColumnType("double");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderPembelianId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("OrderPembelianItem");
                });

            modelBuilder.Entity("ShareModels.OrderPenjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("DeadLine")
                        .HasColumnType("double");

                    b.Property<string>("Discription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GudangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SalesId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GudangId");

                    b.HasIndex("SalesId");

                    b.ToTable("OrderPenjualan");
                });

            modelBuilder.Entity("ShareModels.OrderPenjualanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int?>("OrderPenjualanId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderPenjualanId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("OrderPenjualanItem");
                });

            modelBuilder.Entity("ShareModels.PembayaranPembelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayTo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.Property<double>("PayValue")
                        .HasColumnType("double");

                    b.Property<int?>("PembelianId")
                        .HasColumnType("int");

                    b.Property<string>("RekNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PembelianId");

                    b.ToTable("PembayaranPembelian");
                });

            modelBuilder.Entity("ShareModels.PembayaranPenjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayTo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PayType")
                        .HasColumnType("int");

                    b.Property<double>("PayValue")
                        .HasColumnType("double");

                    b.Property<int?>("PenjualanId")
                        .HasColumnType("int");

                    b.Property<string>("RekNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PenjualanId");

                    b.ToTable("PembayaranPenjualan");
                });

            modelBuilder.Entity("ShareModels.Pembelian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeadLine")
                        .HasColumnType("int");

                    b.Property<int?>("GudangId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("OrderPembelianId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GudangId");

                    b.HasIndex("OrderPembelianId")
                        .IsUnique();

                    b.ToTable("Pembelian");
                });

            modelBuilder.Entity("ShareModels.PembelianItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int?>("PembelianId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PembelianId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("PembelianItem");
                });

            modelBuilder.Entity("ShareModels.Pemindahan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DariId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("TujuanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WaktuPemindahan")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DariId");

                    b.HasIndex("TujuanId");

                    b.ToTable("Pemindahan");
                });

            modelBuilder.Entity("ShareModels.PemindahanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PemindahanId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PemindahanId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("PemindahanItem");
                });

            modelBuilder.Entity("ShareModels.PengembalianPenjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("GudangId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GudangId");

                    b.ToTable("PengembalianPenjualan");
                });

            modelBuilder.Entity("ShareModels.PengembalianPenjualanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int?>("PengembalianPenjualanId")
                        .HasColumnType("int");

                    b.Property<int?>("PenjualanId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PengembalianPenjualanId");

                    b.HasIndex("PenjualanId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("PengembalianPenjualanItem");
                });

            modelBuilder.Entity("ShareModels.Penjualan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Activity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("DeadLine")
                        .HasColumnType("double");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Expedisi")
                        .HasColumnType("double");

                    b.Property<double>("FeeSalesman")
                        .HasColumnType("double");

                    b.Property<int?>("GudangId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderPenjualanId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesmanId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GudangId");

                    b.HasIndex("OrderPenjualanId");

                    b.HasIndex("SalesmanId");

                    b.ToTable("Penjualan");
                });

            modelBuilder.Entity("ShareModels.Penjualanitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int?>("PenjualanId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PenjualanId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("Penjualanitem");
                });

            modelBuilder.Entity("ShareModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CodeArticle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CodeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int?>("MerkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Size")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MerkId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ShareModels.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Thumb")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("ShareModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ShareModels.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NPWP")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telepon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("ShareModels.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Buy")
                        .HasColumnType("double");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<double>("Sell")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("ShareModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ShareModels.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Userrole");
                });

            modelBuilder.Entity("ShareModels.Customer", b =>
                {
                    b.HasOne("ShareModels.Karyawan", "Karyawan")
                        .WithMany()
                        .HasForeignKey("KaryawanId");

                    b.HasOne("ShareModels.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId");

                    b.Navigation("Karyawan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShareModels.IncomingItem", b =>
                {
                    b.HasOne("ShareModels.Pembelian", "Pembelian")
                        .WithMany("Incomingitem")
                        .HasForeignKey("PembelianId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany("Incomingitem")
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Pembelian");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.Karyawan", b =>
                {
                    b.HasOne("ShareModels.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShareModels.OrderPembelian", b =>
                {
                    b.HasOne("ShareModels.Supplier", "Supplier")
                        .WithMany("Orderpembelian")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ShareModels.OrderPembelianItem", b =>
                {
                    b.HasOne("ShareModels.OrderPembelian", "OrderPembelian")
                        .WithMany("Items")
                        .HasForeignKey("OrderPembelianId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany("Orderpembelianitem")
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("OrderPembelian");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.OrderPenjualan", b =>
                {
                    b.HasOne("ShareModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("ShareModels.Gudang", "Gudang")
                        .WithMany()
                        .HasForeignKey("GudangId");

                    b.HasOne("ShareModels.Karyawan", "Sales")
                        .WithMany()
                        .HasForeignKey("SalesId");

                    b.Navigation("Customer");

                    b.Navigation("Gudang");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ShareModels.OrderPenjualanItem", b =>
                {
                    b.HasOne("ShareModels.OrderPenjualan", "OrderPenjualan")
                        .WithMany("Items")
                        .HasForeignKey("OrderPenjualanId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany("Orderpenjualanitem")
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("OrderPenjualan");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.PembayaranPembelian", b =>
                {
                    b.HasOne("ShareModels.Pembelian", "Pembelian")
                        .WithMany("PembayaranPembelian")
                        .HasForeignKey("PembelianId");

                    b.Navigation("Pembelian");
                });

            modelBuilder.Entity("ShareModels.PembayaranPenjualan", b =>
                {
                    b.HasOne("ShareModels.Penjualan", "Penjualan")
                        .WithMany("PembayaranPenjualan")
                        .HasForeignKey("PenjualanId");

                    b.Navigation("Penjualan");
                });

            modelBuilder.Entity("ShareModels.Pembelian", b =>
                {
                    b.HasOne("ShareModels.Gudang", "Gudang")
                        .WithMany()
                        .HasForeignKey("GudangId");

                    b.HasOne("ShareModels.OrderPembelian", "OrderPembelian")
                        .WithOne("Pembelian")
                        .HasForeignKey("ShareModels.Pembelian", "OrderPembelianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gudang");

                    b.Navigation("OrderPembelian");
                });

            modelBuilder.Entity("ShareModels.PembelianItem", b =>
                {
                    b.HasOne("ShareModels.Pembelian", "Pembelian")
                        .WithMany("Items")
                        .HasForeignKey("PembelianId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany("PembelianItem")
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Pembelian");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.Pemindahan", b =>
                {
                    b.HasOne("ShareModels.Gudang", "Dari")
                        .WithMany()
                        .HasForeignKey("DariId");

                    b.HasOne("ShareModels.Gudang", "Tujuan")
                        .WithMany()
                        .HasForeignKey("TujuanId");

                    b.Navigation("Dari");

                    b.Navigation("Tujuan");
                });

            modelBuilder.Entity("ShareModels.PemindahanItem", b =>
                {
                    b.HasOne("ShareModels.Pemindahan", null)
                        .WithMany("Items")
                        .HasForeignKey("PemindahanId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.PengembalianPenjualan", b =>
                {
                    b.HasOne("ShareModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("ShareModels.Gudang", "Gudang")
                        .WithMany()
                        .HasForeignKey("GudangId");

                    b.Navigation("Customer");

                    b.Navigation("Gudang");
                });

            modelBuilder.Entity("ShareModels.PengembalianPenjualanItem", b =>
                {
                    b.HasOne("ShareModels.PengembalianPenjualan", null)
                        .WithMany("Items")
                        .HasForeignKey("PengembalianPenjualanId");

                    b.HasOne("ShareModels.Penjualan", "Penjualan")
                        .WithMany()
                        .HasForeignKey("PenjualanId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Penjualan");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.Penjualan", b =>
                {
                    b.HasOne("ShareModels.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("ShareModels.Gudang", "Gudang")
                        .WithMany()
                        .HasForeignKey("GudangId");

                    b.HasOne("ShareModels.OrderPenjualan", "OrderPenjualan")
                        .WithMany()
                        .HasForeignKey("OrderPenjualanId");

                    b.HasOne("ShareModels.Karyawan", "Salesman")
                        .WithMany()
                        .HasForeignKey("SalesmanId");

                    b.Navigation("Customer");

                    b.Navigation("Gudang");

                    b.Navigation("OrderPenjualan");

                    b.Navigation("Salesman");
                });

            modelBuilder.Entity("ShareModels.Penjualanitem", b =>
                {
                    b.HasOne("ShareModels.Penjualan", "Penjualan")
                        .WithMany("Items")
                        .HasForeignKey("PenjualanId");

                    b.HasOne("ShareModels.Product", "Product")
                        .WithMany("PenjualanItem")
                        .HasForeignKey("ProductId");

                    b.HasOne("ShareModels.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Penjualan");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ShareModels.Product", b =>
                {
                    b.HasOne("ShareModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("ShareModels.Merk", "Merk")
                        .WithMany()
                        .HasForeignKey("MerkId");

                    b.HasOne("ShareModels.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Category");

                    b.Navigation("Merk");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ShareModels.ProductImage", b =>
                {
                    b.HasOne("ShareModels.Product", null)
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("ShareModels.Unit", b =>
                {
                    b.HasOne("ShareModels.Product", null)
                        .WithMany("Units")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("ShareModels.UserRole", b =>
                {
                    b.HasOne("ShareModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("ShareModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShareModels.OrderPembelian", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Pembelian");
                });

            modelBuilder.Entity("ShareModels.OrderPenjualan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShareModels.Pembelian", b =>
                {
                    b.Navigation("Incomingitem");

                    b.Navigation("Items");

                    b.Navigation("PembayaranPembelian");
                });

            modelBuilder.Entity("ShareModels.Pemindahan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShareModels.PengembalianPenjualan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShareModels.Penjualan", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PembayaranPenjualan");
                });

            modelBuilder.Entity("ShareModels.Product", b =>
                {
                    b.Navigation("Incomingitem");

                    b.Navigation("Orderpembelianitem");

                    b.Navigation("Orderpenjualanitem");

                    b.Navigation("PembelianItem");

                    b.Navigation("PenjualanItem");

                    b.Navigation("ProductImage");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("ShareModels.Supplier", b =>
                {
                    b.Navigation("Orderpembelian");
                });

            modelBuilder.Entity("ShareModels.User", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
