name: ANDROID

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: macos-12
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup keystore file
        shell: bash
        run: |
          mkdir -pv production/whatsnew
          echo "ini adalah yang baru" > ./production/whatsnew/whatsnew-id-ID
         
          ls
      
      # - name: Setup .NET 7
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 7.0.x
      #     include-prerelease: true
     
      # - name: Install .NET MAUI
      #   shell: bash
      #   run: |
      #     dotnet nuget locals all --clear 
      #     dotnet workload install maui-android --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      #     dotnet workload install android --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    
      # - name: Restore Dependencies
      #   run: dotnet restore ApsMobileApp/ApsMobileApp.csproj

      # - name: Build MAUI Android
      #   run: dotnet build ApsMobileApp/ApsMobileApp.csproj -c Release -f net7.0-android /p:AndroidSigningKeyStore=ocph23.keystore /p:AndroidSigningKeyAlias=Ocph23 /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" --no-restore

      # - name: Upload Android Artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: android-ci-build
      #     path: ApsMobileApp/bin/Release/net7.0-android/*Signed.aab


      # - name: Get appbundle from artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: android-ci-build

      # - name: Create service_account.json
      #   run: |
      #     ls
      #     echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      # - name: Deploy to Production
      #   uses: r0adkll/upload-google-play@v1
      #   with:
      #     serviceAccountJson: service_account.json
      #     packageName: com.ocph23.apsmobileapp
      #     releaseFiles: com.ocph23.apsmobileapp-Signed.aab
      #     track: production
      #     whatsNewDirectory: distribution/whatsnew
          